from fpdf import FPDF
import datetime

class MedicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Breast Cancer Classification Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_download_link(input_data, prediction_text, recommendation=None):
    pdf = MedicalReport()
    pdf.add_page()
    
    # Metadata
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(10)
    
    # Prediction Section
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="Diagnosis Result", ln=True)
    pdf.set_font("Arial", size=12)
    
    # Color logic could be simulating highlighting, but for simple PDF text:
    result_str = f"The analysis indicates: {prediction_text}"
    pdf.multi_cell(0, 10, txt=result_str)
    pdf.ln(10)
    
    # Input Data Section
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="Patient Metrics", ln=True)
    pdf.set_font("Arial", size=12)
    
    # Display features in a list
    feature_names = [
        "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape",
        "Marginal Adhesion", "Single Epithelial Cell Size", "Bland Chromatin",
        "Normal Nucleoli", "Mitoses"
    ]
    
    for name, value in zip(feature_names, input_data):
        pdf.cell(0, 8, txt=f"- {name}: {value}/10", ln=True)
        
    pdf.ln(10)

    # AI Recommendation Section
    if recommendation:
        pdf.add_page() # Start recommendations on a new page to ensure enough space
        pdf.set_font("Arial", 'B', size=14)
        pdf.cell(0, 10, txt="AI Medical Recommendations", ln=True)
        pdf.ln(5)
        
        pdf.set_font("Arial", size=11)
        
        # Simple Markdown Cleanup
        # Remove bold markers
        text = recommendation.replace('**', '').replace('__', '')
        # Handle headers slightly (replace with uppercase or spacing)
        # We'll just strip the # characters and let the visual spacing handle it
        text = text.replace('### ', '').replace('## ', '')
        
        # Basic cleanup for latin-1 (common issue with FPDF and AI text)
        # Replace common unicode chars that fail in latin-1
        text = text.replace('’', "'").replace('–', "-").replace('—', "-")
        clean_rec = text.encode('latin-1', 'replace').decode('latin-1')
        
        # Use Justified alignment ('J')
        pdf.multi_cell(0, 6, txt=clean_rec, align='J')
        pdf.ln(10)

    pdf.set_y(-30) # Position disclaimer at bottom if space permits, or just output it
    pdf.set_font("Arial", 'I', size=9)
    pdf.multi_cell(0, 5, txt="DISCLAIMER: This report is generated by an AI model and should not be considered a definitive medical diagnosis. Please consult a specialist.", align='C')
    
    return pdf.output(dest='S').encode('latin-1')
